- name: copy mongodb repo 
  ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: installed

- name: update mongodb conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Start service mongod, if not started
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

# - name: dwonload and extract
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/mongodb/archive/main.zip
#     dest: /tmp
#     remote_src: yes  

- name: Run tasks other download and extract mongo
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Run a js file 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

  

# - name: Run a js file 
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/users.js"
#     idempotent: yes 

- name: Run tasks other download and extract mongo
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname